id:
  4
seed:
  2019
k_folds_seed:
  100
features_table:
  papers_features
labels_table:
  papers_rgs_wide
unique_id:
  recordid
data_type:
  flat
target:
  inregister
existing_features:
  - tokens_no_stopwords
generated_features:
  ~
model_type:
  rf_tfidf
hyperparameters:
  n_estimators: [10, 100]
  max_depth: [10, 50, 100]
  max_features: ['auto']
  min_samples_leaf: [5, 10, 20]
  n_jobs: [8]
query:
  ~
condition:
  ~
train_neg_n:
  ~
test_perc:
  0.2
