id:
  6
seed:
  2019
k_folds_seed:
  100
features_table:
  papers_features
labels_table:
  papers_rgs_wide
unique_id:
  recordid
data_type:
  flat
target:
  inregister
existing_features:
  - average_embeddings
generated_features:
  ~
model_type:
  elasticnet_embeddings
hyperparameters:
  alpha: [0.1, 0.01, 0.001, 0.0001, 0.00001, 0.000001, 0.0000001]
  lambda: [0.2, 0.4, 0.6, 0.8, 1.0]
query:
  ~
condition:
  ~
train_neg_n:
  ~
test_perc:
  0.2
